
-- auto-generated definition
create table gadgettype
(
    id   integer generated by default as identity
        constraint gadgettype_pkey
            primary key,
    icon varchar(128),
    name varchar(128)
);

alter table gadgettype
    owner to postgres;



-- alter table `gadgets`
--     add column `gadget_type_id` INT NOT NULL after `place_id`,
--     add CONSTRAINT `fk_gadget__gadget_types`
--         FOREIGN KEY (`gadget_type_id`)
--             REFERENCES `gadget_types` (`id`);