-- auto-generated definition
create table places_table
(
    id      integer generated by default as identity
        constraint places_table_pkey
            primary key,
    address varchar(128),
    image   varchar(255),
    name    varchar(128)
);

alter table places_table
    owner to postgres;

