-- auto-generated definition
create table cart_items
(
    id integer generated by default as identity
        constraint cart_items_pkey
            primary key,
    quantity    integer not null,
    customer_id integer
        constraint fkdagcsk6v6x4n1kxw3rkp57921
            references customers,
    tovar_id    bigint
        constraint fkaioha5npna6bohqcccnfjc760
            references tovars
);

alter table cart_items
    owner to postgres;



